# Generated by Django 4.1.7 on 2023-08-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMixin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(),
        ),
    ]
